# Generated by Django 5.2.8 on 2025-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='setor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
