# Generated by Django 5.2.8 on 2025-11-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuariocustomizado_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
