# Generated by Django 5.2.8 on 2025-12-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuariocustomizado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Gestor', 'Gestor'), ('Vendedor', 'Vendedor'), ('Separador', 'Separador')], help_text='Define o nível de acesso do usuário no sistema.', max_length=20, null=True),
        ),
    ]
