# Generated by Django 5.2.8 on 2025-11-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('responsavel', models.CharField(max_length=255, verbose_name='A/C (Aos Cuidados de)')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Processo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo_amostra', models.CharField(choices=[('preforma_pet', 'Pré-forma PET'), ('garrafa_finalizada', 'Garrafa Finalizada'), ('tampa_plastica', 'Tampa Plástica'), ('rotulo', 'Rótulo'), ('materia_prima', 'Matéria Prima'), ('outro', 'Outro')], max_length=50)),
                ('tipo_transporte', models.CharField(choices=[('correios', 'Correios'), ('carga', 'Carga'), ('balcao', 'Balcão')], default='Correios', max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('nao_atribuido', 'Não Atribuído'), ('atribuido', 'Atribuído'), ('em_separacao', 'Em Separação'), ('pendente', 'Pendente'), ('pronto_envio', 'Pronto para Envio'), ('em_rota', 'Em Rota de Entrega'), ('entregue', 'Entregue'), ('nao_entregue', 'Não Entregue')], default='nao_atribuido', max_length=30)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='samples.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('icone', models.CharField(default='bi-circle', max_length=50)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='samples.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('encaminhar_gestao', models.BooleanField(default=False, verbose_name='Encaminhar para Gestão')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='samples.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_processos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='samples.processo')),
            ],
        ),
    ]
