# Generated by Django 5.2.8 on 2025-11-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_comentario_autor_alter_processo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tipo_amostra',
        ),
        migrations.AddField(
            model_name='processo',
            name='codigo_pedido_iniflex',
            field=models.CharField(blank=True, help_text='Insira o número do pedido gerado no Iniflex para referência.', max_length=50, null=True, verbose_name='Cód. Pedido Iniflex'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipos_amostra',
            field=models.ManyToManyField(related_name='processos', to='samples.tipoamostra'),
        ),
    ]
