# Generated by Django 5.2.8 on 2025-11-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_tipoamostra_remove_processo_tipo_amostra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoamostra',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='tipoamostra',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Menor número aparece primeiro'),
        ),
    ]
