# Generated by Django 5.2.8 on 2025-11-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_processo_responsavel_separacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('nao_atribuido', 'Não Atribuído'), ('atribuido', 'Atribuído'), ('em_separacao', 'Em Separação'), ('pendente', 'Pendente'), ('pronto_envio', 'Pronto para Envio'), ('em_rota', 'Em Rota de Entrega'), ('entregue', 'Entregue'), ('nao_entregue', 'Não Entregue'), ('cancelado', 'Cancelado')], default='nao_atribuido', max_length=30),
        ),
    ]
