# Generated by Django 5.2.8 on 2025-12-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_processo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoamostra',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tipo de Amostra', 'verbose_name_plural': 'Tipos de Amostra'},
        ),
        migrations.AlterField(
            model_name='tipoamostra',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Menor número aparece primeiro na lista de seleção'),
        ),
    ]
